<?php
/**
 * Created by PhpStorm.
 * User: txkj
 * Date: 17/2/28
 * Time: 下午5:08
 */

namespace app\admin\Controller;

use app\builder\controller\tableBuilder;

class User extends core
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->Model = new \app\admin\model\User();
    }


    /**
     * 显示资源列表
     *
     * @return \think\Response
     */
    public function index()
    {
        $builder = new tableBuilder();
        $table = array('id' => 'grid', 'url' => 'user/dataList', 'pagination' => true);
        $column1 = array('title' => '用户ID', 'field' => 'id');
        $column2 = array('title' => '用户名', 'field' => 'username');
        $column3 = array('title' => '用户角色', 'field' => 'role_name');
        $column4 = array('title' => '创建时间', 'field' => 'create_time');
        $column5 = array('title' => '最后登录时间', 'field' => 'login_time');
        $column6 = array('title' => '最后登录IP', 'field' => 'login_ip');
        $column7 = array('title' => '用户状态', 'field' => 'status');
        $column8 = array('title' => '备注', 'field' => 'remark');
        $column9 = array('field' => 'operate', 'button' => $builder->addButton('edit')->addButton('delete')->getButton());
        $columns = array(
            array('column' => $column1),
            array('column' => $column2),
            array('column' => $column3),
            array('column' => $column4),
            array('column' => $column5),
            array('column' => $column6),
            array('column' => $column7),
            array('column' => $column8),
            array('column' => $column9, 'type' => 'operate'),
        );

        $toolbar = array('id' => 'tool_bar',
            'list' => $builder->addButton('search')->addButton('create')->addButton('refresh')->getButton());
        $builder->addTable($table, $columns, $toolbar);

        $userTable = $builder->getTable();

        $this->assign('table', $userTable);
        return view('./template/index_table.tpl');
    }

    protected function searchView()
    {
        return parent::searchView(); // TODO: Change the autogenerated stub
    }

    protected function resourcesView()
    {
        return parent::resourcesView(); // TODO: Change the autogenerated stub
    }


}